"""Gaussian near field with a hard (knife) edge along x, imaged onto the first mirror.
Question: are the colours generated by SPM cleaner (less edge diffraction) than the fundamental?

Resumable:  python clipped_gauss_profiles.py [max_seconds]      -> figures in ./out_clipped/
Only 1D plots: x profiles (cuts through y = 0) for several wavelengths, at the cell centre,
at the mirror (before the bounce) and in the far field, for selected passes.
"""
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import thunder4d as m

lam0, fwhm = 1030e-9, 200e-15
ENERGY = 1.3e-3                # transmitted energy (after the edge)
EDGE = 0.5                     # knife edge at x = +EDGE * w_mirror (blocks x > edge, ~16 % of a gaussian)
gas = m.Material("Ar", 1.0)
cell = m.MPCCell.herriott(R=0.5, N=10, k=3, medium=gas)               # 20 passes
grid = m.suggest_grid(cell, lam0, 900e-9, 1200e-9, fwhm, box_factor=14)

WAVELENGTHS = [1000e-9, 1015e-9, 1030e-9, 1045e-9, 1060e-9]
BANDWIDTH = 2e-9
PASSES = [0, 1, 3, 5, 10, 15, 20]

E = m.gaussian_spectrum(grid, fwhm_fs=fwhm * 1e15)
probe = m.Pulse.at_focus(grid, E, m.Beam(m.gaussian(1e-3)), ENERGY)
mm = cell.match(probe, verbose=False)
wm = mm["w_mirror"]
beam = m.Beam(m.knife_edge(m.gaussian(wm), EDGE * wm, axis="x", side="+"))
pulse = m.Pulse.imaged_near_field(grid, E, beam, ENERGY, cell)
cell.match(pulse)                                                   # report with the real (clipped) pulse

sim = m.MPCSimulation(pulse, cell, phi_max=0.02, mode_reference=mm["w0"],
                      profile_wavelengths=WAVELENGTHS, profile_bandwidth=BANDWIDTH)
ckpt = "ckpt_clipped.pkl"
if os.path.exists(ckpt):
    sim.resume(ckpt)
if not sim.done:
    sim.run(max_seconds=float(sys.argv[1]) if len(sys.argv) > 1 else None)
    sim.checkpoint(ckpt)
    if not sim.done:
        print("time budget reached: run again to continue")
        sys.exit(0)
    sim.save("run_clipped.npz", include_field=False)

# ------------------------------------------------------------------ figures (1D only)
out = "out_clipped"
os.makedirs(out, exist_ok=True)
h = sim.history
P = list(h["pass"])
x = sim.prof_coord * 1e6
th = sim.theta * 1e3
band = np.array(h["band_energy"])
labels = [f"{l*1e9:.0f} nm" for l in WAVELENGTHS] + ["global"]
colors = plt.cm.turbo(np.linspace(0.1, 0.9, len(WAVELENGTHS))).tolist() + ["k"]
present = band[:, :-1] / band[:, -1:] > 1e-4          # colour exists at that pass
mirror = {p: v for p, v in zip(P, h["prof_mirror"]) if v is not None}
data = {
    "centre": ({p: v for p, v in zip(P, h["prof_near"])}, x, 3 * mm["w0"] * 1e6, "x (um)"),
    "mirror": (mirror, x, 2.2 * wm * 1e6, "x (um)"),
    "far_field": ({p: v for p, v in zip(P, h["prof_far"])}, th,
                  3 * lam0 / (np.pi * mm["w0"]) * 1e3, "theta_x (mrad)"),
}

for log in (False, True):
    for tag, (prof, coord, lim, xl) in data.items():
        passes = [p for p in PASSES if p in prof]
        fig, axs = plt.subplots(1, len(passes), figsize=(3.0 * len(passes), 3.3), sharey=True,
                                constrained_layout=True)
        for a, p in zip(axs, passes):
            k = P.index(p)
            for i, lab in enumerate(labels):
                if i < len(WAVELENGTHS) and not present[k, i]:
                    continue
                y = prof[p][i].astype(float)
                y = y / y.max()
                a.plot(coord, y, color=colors[i], ls="--" if lab == "global" else "-",
                       lw=1.6 if lab == "global" else 1.1, label=lab)
            if tag != "far_field":
                a.axvline(EDGE * wm * 1e6 * (1 if tag == "mirror" else np.nan), color="0.6", lw=0.8, ls=":")
            a.set_xlim(-lim, lim)
            a.set_title(f"pass {p}" + (" (before bounce)" if tag == "mirror" else ""), fontsize=9)
            a.set_xlabel(xl)
            if log:
                a.set_yscale("log")
                a.set_ylim(1e-4, 1.5)
        axs[0].set_ylabel("normalised intensity (cut y = 0)")
        axs[-1].legend(fontsize=7, loc="upper right")
        fig.suptitle(f"clipped gaussian - {tag}", fontsize=10)
        fig.savefig(f"{out}/lines_{tag}{'_log' if log else ''}.png", dpi=130)
        plt.close(fig)

# fundamental-mode fraction of each colour vs pass + output spectrum
lam_h = sim.lam
eta = np.array(h["eta00"])
fig, axs = plt.subplots(1, 2, figsize=(10, 3.6), constrained_layout=True)
for i, l in enumerate(WAVELENGTHS):
    e = np.array([np.interp(l, lam_h, row) for row in eta])
    e[~present[:, i]] = np.nan
    axs[0].plot(P, e, "o-", color=colors[i], ms=3, label=labels[i])
axs[0].plot(P, h["eta00_total"], "k--", label="global")
axs[0].set_xlabel("pass"); axs[0].set_ylabel("HG00 fraction (cell centre)"); axs[0].legend(fontsize=7)
for k, p in enumerate(P):
    if p in (0, 5, 10, 20):
        S = h["spectrum"][k]
        axs[1].semilogy(lam_h * 1e9, S / S.max(), label=f"pass {p}")
axs[1].set_xlim(960, 1100); axs[1].set_ylim(1e-3, 1.2); axs[1].set_xlabel("wavelength (nm)")
axs[1].legend(fontsize=7); axs[1].set_title("spatially integrated spectrum")
fig.savefig(f"{out}/eta00_and_spectrum.png", dpi=130)

S = h["spectrum"][-1] / h["spectrum"][-1].max()
for t in (0.1, 0.01):
    i = np.nonzero(S > t)[0]
    print(f"output spectrum above {t:g}: {lam_h[i[0]]*1e9:.0f}-{lam_h[i[-1]]*1e9:.0f} nm")
print(f"figures in {out}/")
